[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "safenode"
version = "0.112.3"
description = "SAFE Network Node"
requires-python = ">=3.8"

[tool.maturin]
features = ["extension-module"]
module-name = "_safenode"
python-source = "python"
bindings = "pyo3"
manifest-path = "Cargo.toml"
python-packages = ["safenode"]
include = ["python/safenode"]
sdist-include = ["python/safenode"]

[tool.maturin.development]
path = "python"
requires = ["pip>=24.3.1"]
